# A generic, single database configuration.

[alembic]
script_location = %(here)s/migrations
file_template = %%(year)02d-%%(month)02d-%%(day)02d_%%(hour)02d-%%(minute)02d_%%(rev)s_%%(slug)s
prepend_sys_path = .
path_separator = os
sqlalchemy.url = driver://user:pass@localhost/dbname
version_locations = %(here)s/migrations/versions
recursive_version_locations = true

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
